versio: "3.0"
servises: 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    conteiner_name: realworld-docker-frontend
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    enviroment:
      - CHOKIDAR_USEPOLLING=true
    volume:
      - './frontend:/usr/src/app'
      - '/app/node_modules'
  api:
    build: ./api
    command: npm run dev
    volume:
      - ./api/src:/usr/src/app/src